---
title: "Subturf Maps"
author: "Richard J. Telford"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: pdf_document
classoption: a4paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

#load packages
library("tidyverse")
library("DBI")# also needs RMySQL installed

knitr::read_chunk("R/load_comm.R")
knitr::read_chunk("R/load_subturfcomm.R")
knitr::read_chunk("start_here.R")
```

```{r load_comm}
```

```{r load_subturfcomm}
```

```{r load_community}
```

```{r importChunk, echo = FALSE}

subturf_thin <- load_subturfcomm(con = con)
#merge cover amd subturf
subturf_cover_thin <- left_join(subturf_thin, cover_thin)

```

#Subturf maps

```{r, fig.height=11, fig.width = 7}
plyr::d_ply(subturf_cover_thin, plyr::.(turfID), function(df){
  print(
  ggplot(df, aes(x = (subTurf - 1) %/% 5, y = (subTurf - 1) %% 5, fill = cover, colour = "outline")) +
    geom_tile() +
    facet_grid(species ~ year) +
    ggtitle(paste(df$turfID[1], "subturf map")) +
    scale_x_continuous(expand = c(0, 0)) +
    scale_y_continuous(expand = c(0, 0)) +
    scale_fill_distiller(type = "seq", palette = "Greens", direction = 1) + 
    scale_colour_manual(values = "black", guide = "none") + 
    theme(
      axis.text = element_blank(), 
      axis.title = element_blank(), 
      axis.ticks = element_blank(),
      strip.text.y = element_text(angle = 0)
      )
  
  )
    cat("\n")
})
```